app:
  server:
    url: http://localhost:9991
  log:
    name: server1,server2
    path: E:\\project\\log-monitor\\log-reader\\src\\test\\test.log,E:\\project\\log-monitor\\log-reader\\src\\test\\test2.log
